// <auto-generated />
namespace DeptStudentApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class studentdeptmodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(studentdeptmodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201809111831237_studentdeptmodel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
